config/routes.rb
Rails.application.routes.draw do
  resources :styles
  get 'ngbeerlist', to:'beers#nglist'
  get 'ngbrewerylist', to:'breweries#nglist'
  get 'beerlist', to:'beers#list'
  resources :places, only:[:index, :show]

  post 'places', to:'places#search'
  
  
  resources :memberships, only: [:index, :new, :create, :destroy]
  resources :beer_clubs
  resources :users
  root 'breweries#index'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  resource :session, only: [:new, :create, :destroy]
  resources :ratings, only: [:index, :new, :create, :destroy]
  resources :beers
  resources :breweries

end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
  include RatingAverage
  
  has_many :beers
  has_many :ratings, through: :beers
  
  validates :name, presence: true
  
  validates :year, numericality: { greater_than_or_equal_to: 1042,
                                      less_than_or_equal_to: Proc.new{ Time.now.year },
                                               only_integer: true }
  scope :active, -> { where active:true }
  scope :retired, -> { where active:[nil,false] }  
  
  def self.top(n)    
     sorted_by_rating_in_desc_order = Brewery.all.sort_by{ |b| -(b.average_rating) }
     sorted_by_rating_in_desc_order.take(3)
  end                                        
  
  def to_s
    "#{self.name}"
  end
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :set_order_and_reverse, only: [:index]
  before_action :set_brewery, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate, only: [:destroy]
  
  # GET /ngbrewerieslist
  def nglist
  end

  # GET /breweries
  # GET /breweries.json
  def index
    unless fragment_exist?( 'brewerylist-#{@order}-#{@reverse}' )
      # json
      @breweries = Brewery.all
      
      #(byebug)
      
      @active_breweries = case @order
        when 'name' then Brewery.active.sort_by &:name
        when 'year' then Brewery.active.sort_by &:year  
      end
      @retired_breweries = case @order
        when 'name' then Brewery.retired.sort_by &:name
        when 'year' then Brewery.retired.sort_by &:year  
      end
      
      if @reverse
        @active_breweries.reverse!
        @retired_breweries.reverse!
      end
      
      #@active_breweries = Brewery.active #where(active:true)
      #@retired_breweries = Brewery.retired #where(active:[nil, false])
    end
  end

  # GET /breweries/1
  # GET /breweries/1.json
  def show
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries
  # POST /breweries.json
  def create
    ["brewerylist-name-false", "brewerylist-name-true", "brewerylist-year-false", "brewerylist-year-true"].each{ |f| expire_fragment(f) }
    
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to @brewery, notice: 'Brewery was successfully created.' }
        format.json { render :show, status: :created, location: @brewery }
      else
        format.html { render :new }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1
  # PATCH/PUT /breweries/1.json
  def update
    ["brewerylist-name-false", "brewerylist-name-true", "brewerylist-year-false", "brewerylist-year-true"].each{ |f| expire_fragment(f) }
    
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to @brewery, notice: 'Brewery was successfully updated.' }
        format.json { render :show, status: :ok, location: @brewery }
      else
        format.html { render :edit }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    ["brewerylist-name-false", "brewerylist-name-true", "brewerylist-year-false", "brewerylist-year-true"].each{ |f| expire_fragment(f) }
    
    @brewery.destroy
    respond_to do |format|
      format.html { redirect_to breweries_url, notice: 'Brewery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_order_and_reverse
      @order = params[:order] || 'name'
      if session[:order_reverse].nil?
        @reverse = session[:order_reverse] = false
      else
        @reverse = session[:order_reverse] = !session[:order_reverse]
      end
    end
  
    # Use callbacks to share common setup or constraints between actions.
    def set_brewery
      @brewery = Brewery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brewery_params
      params.require(:brewery).permit(:name, :year, :active)
    end
    
    def authenticate
      admin_accounts = { "admin" => "secret", "pekka" => "beer" }
      
      authenticate_or_request_with_http_basic do |username, password|
        admin_accounts.each do |k, v| 
          if username == k and password == v 
            true 
          end
        end
      end
    end
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_form.html.erb
<%= form_for(@brewery) do |f| %>
  <% if @brewery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
      <% @brewery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :active %>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit class:'btn btn-primary'%>
  </div>
<% end %>

app/views/breweries/_list.html.erb
<table class="table table-hover">
  <thead>
  <tr>
    <th><%= link_to 'Name', breweries_path(order:"name") %></th>
    <th><%= link_to 'Year', breweries_path(order:"year") %></th>
  </tr>
  </thead>

  <tbody>
  <% breweries.each do |brewery| %>
      <tr>
        <td><%= link_to brewery.name, brewery %></td>
        <td><%= brewery.year %></td>
        <td></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/breweries/edit.html.erb
<h1>Editing Brewery</h1>

<%= render 'form' %>

<%= link_to 'Show', @brewery %> |
<%= link_to 'Back', breweries_path %>

app/views/breweries/index.html.erb
<h1>Breweries</h1>

<!--
<div style="border-style: solid;">
  brewerylist-name-false: <%= ActionController::Base.new.fragment_exist?( 'brewerylist-name-false' ) %>
  <br>
  brewerylist-name-true: <%= ActionController::Base.new.fragment_exist?( 'brewerylist-name-true' ) %>
  <br>
  brewerylist-year-false: <%= ActionController::Base.new.fragment_exist?( 'brewerylist-year-false' ) %>
  <br>
  brewerylist-year-true: <%= ActionController::Base.new.fragment_exist?( 'brewerylist-year-true' ) %>
  <br>
  current: <%= "brewerylist-#{@order}-#{@reverse}" %>
</div>
-->

<% cache "brewerylist-#{@order}-#{@reverse}", skip_digest: true do %>

  <h2>Active</h2>
  
  <p> Number of active breweries: <%= @active_breweries.count %> </p>
  
    <%= render 'list', breweries: @active_breweries %>
  
  <h2>Retired</h2>
  
  <p> Number of retired breweries: <%= @retired_breweries.count %> </p>
  
    <%= render 'list', breweries: @retired_breweries %>
  
  <br>
  
  <%= link_to 'New Brewery', new_brewery_path, class:"btn btn-primary"  %>

<% end %>

app/views/breweries/new.html.erb
<h1>New Brewery</h1>

<%= render 'form' %>

<%= link_to 'Back', breweries_path %>

app/views/breweries/nglist.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.5/angular.min.js"></script>
<script>
  var myApp = angular.module('myApp', []);

  myApp.controller("BreweriesController", function ($scope, $http) {
    $http.get('breweries.json').success( function(data, status, headers, config) {
      $scope.breweries = data;
    });

    $scope.order = 'name';

    $scope.sort_by = function (order){
      $scope.order = order;
      console.log(order);
    }

    $scope.searchText = '';
  });
</script>

<h2>Beers</h2>

<div ng-app="myApp" ng-controller="BreweriesController">

  search:  <input ng-model="searchText">

  <table class="table table-hover">
    <thead>
    <th> <a ng-click="sort_by('name')">name</a> </th>
    <th> <a ng-click="sort_by('year')">year</a> </th>
    </thead>
    <tr ng-repeat="brewery in breweries| orderBy:order | filter:searchText">
      <td>{{brewery.name}}</td>
      <td>{{brewery.year}}</td>
    </tr>
  </table>

</div>

app/views/breweries/show.html.erb
<% cache @brewery do %>

  <h2><%= @brewery.name %>
    <% if not @brewery.active  %>
        <span class="label label-info">retired</span>
    <% end %>
  </h2>
  
  <p>
    <em>Established year:</em>
    <%= @brewery.year %>
  </p>
  
  <p>Number of beers <%= @brewery.beers.count%> </p>
  
  <ul>
   <% @brewery.beers.each do |beer| %>
     <li><%= link_to beer.name, beer %></li>
   <% end %>
  </ul>
  
  <% if @brewery.ratings.empty? %>
      <p>beers of the brewery have not yet been rated! </p>
  <% else %>
      <p>Has <%= pluralize(@brewery.ratings.count,'rating') %>, average <%= @brewery.average_rating %> </p>
  <% end %>

<% end %>

<% if current_user %>
  <%= link_to 'Edit', edit_brewery_path(@brewery), class:"btn btn-primary"  %>
  <%= link_to 'Destroy', @brewery, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger"  %>
<% end %>